### ISSUE TITLE
Exception on dice rolls

### ISSUE THREAD

**Issue by RedMoikle** [RedMoikle/GameOfUr#2]
An exception is raised after every dice roll:
```
# Traceback (most recent call last):
#   File "E:\github_E\GameOfUr\main.py", line 235, in roll_dice
#     rolled_values = [die.roll() for die in self.dice]
#   File "E:\github_E\GameOfUr\game_pieces.py", line 257, in roll
#     self.transform.rotate.set((0, random.random() * 360, 109.47 * rolled_value))
# AttributeError: 'NoneType' object has no attribute 'rotate'
```

why is the dice transform None? and how is the game still functioning perfectly well in spite of this?

**Comment by RedMoikle** [comment]
This does not seem to be happening now. I will need to test this again on my other device.

**Comment by RedMoikle** [comment]
Confirmed, this occurs because the old interface callbacks are not removed when the game is closed.
